name: starter
on:
  push: 
    branches: ["main"]
  workflow_dispatch:

jobs:
  az-cli:
    name: "azure setup"
    runs-on: ubuntu-latest
    steps:
    - name: setup
      run: echo "az cli"

    - name: print vars
      run: echo vars
    
  
